# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainwindow.sizePolicy().hasHeightForWidth())
        mainwindow.setSizePolicy(sizePolicy)
        mainwindow.setMinimumSize(QtCore.QSize(800, 600))
        mainwindow.setMaximumSize(QtCore.QSize(800, 600))
        mainwindow.setWindowTitle("Inventory 0.91b")
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.addfood = QtWidgets.QPushButton(self.centralwidget)
        self.addfood.setGeometry(QtCore.QRect(0, 0, 131, 51))
        self.addfood.setObjectName("addfood")
        self.editfood = QtWidgets.QPushButton(self.centralwidget)
        self.editfood.setGeometry(QtCore.QRect(130, 0, 131, 51))
        self.editfood.setObjectName("editfood")
        self.addrecipe = QtWidgets.QPushButton(self.centralwidget)
        self.addrecipe.setGeometry(QtCore.QRect(270, 0, 131, 51))
        self.addrecipe.setObjectName("addrecipe")
        self.editrecipe = QtWidgets.QPushButton(self.centralwidget)
        self.editrecipe.setGeometry(QtCore.QRect(400, 0, 131, 51))
        self.editrecipe.setObjectName("editrecipe")
        self.addinv = QtWidgets.QPushButton(self.centralwidget)
        self.addinv.setGeometry(QtCore.QRect(540, 0, 131, 51))
        self.addinv.setObjectName("addinv")
        self.consumeinv = QtWidgets.QPushButton(self.centralwidget)
        self.consumeinv.setGeometry(QtCore.QRect(670, 0, 131, 51))
        self.consumeinv.setObjectName("consumeinv")
        self.plaincalories = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaincalories.setGeometry(QtCore.QRect(170, 130, 331, 31))
        self.plaincalories.setTabChangesFocus(True)
        self.plaincalories.setObjectName("plaincalories")
        self.plainfoodname = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainfoodname.setGeometry(QtCore.QRect(170, 90, 331, 31))
        self.plainfoodname.setTabChangesFocus(True)
        self.plainfoodname.setObjectName("plainfoodname")
        self.plainserving = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainserving.setGeometry(QtCore.QRect(170, 170, 331, 31))
        self.plainserving.setTabChangesFocus(True)
        self.plainserving.setObjectName("plainserving")
        self.plainvita = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainvita.setGeometry(QtCore.QRect(170, 210, 331, 31))
        self.plainvita.setTabChangesFocus(True)
        self.plainvita.setObjectName("plainvita")
        self.plainprotein = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainprotein.setGeometry(QtCore.QRect(170, 250, 331, 31))
        self.plainprotein.setTabChangesFocus(True)
        self.plainprotein.setObjectName("plainprotein")
        self.plaincarbs = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaincarbs.setGeometry(QtCore.QRect(170, 290, 331, 31))
        self.plaincarbs.setTabChangesFocus(True)
        self.plaincarbs.setObjectName("plaincarbs")
        mainwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        self.addfood.setText(_translate("mainwindow", "Add Food"))
        self.editfood.setText(_translate("mainwindow", "Edit Food"))
        self.addrecipe.setText(_translate("mainwindow", "Add Recipe"))
        self.editrecipe.setText(_translate("mainwindow", "Edit Recipe"))
        self.addinv.setText(_translate("mainwindow", "Inv. Add"))
        self.consumeinv.setText(_translate("mainwindow", "Inv. Consume"))
        self.plaincalories.setPlainText(_translate("mainwindow", "Calories"))
        self.plainfoodname.setPlainText(_translate("mainwindow", "Food name"))
        self.plainserving.setPlainText(_translate("mainwindow", "Serving"))
        self.plainvita.setPlainText(_translate("mainwindow", "Vit. A"))
        self.plainprotein.setPlainText(_translate("mainwindow", "Protein"))
        self.plaincarbs.setPlainText(_translate("mainwindow", "Carbs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainwindow = QtWidgets.QMainWindow()
    ui = Ui_mainwindow()
    ui.setupUi(mainwindow)
    mainwindow.show()
    sys.exit(app.exec_())
